language: "perl"

perl:
  - "5.14"
  - "5.10"

env:
  - COVERALLS=true
  - COVERALLS=false

sudo: false

addons:
  apt:
    packages:
    - unzip

before_install:
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-rest.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-funcgen.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-io.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-vep.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone --branch version/2.4 --depth 1 https://github.com/Ensembl/ensembl-hive.git
    - ln -s . ensembl-compara
    - git clone --branch v1.6.x --depth 1 https://github.com/bioperl/bioperl-live
    - git clone --branch master --depth 1 https://github.com/samtools/tabix.git
    - git clone --branch master --depth 1 https://github.com/samtools/htslib.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/Bio-HTS


install:
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ensembl/cpanfile .
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ensembl-rest/cpanfile .
    - cpanm -v --installdeps --notest .
    - cpanm -n Devel::Cover::Report::Coveralls
    - cp -f travisci/MultiTestDB.conf.travisci  modules/t/MultiTestDB.conf
    - cp -f ensembl-rest/travisci/MultiTestDB.conf.travisci ensembl-rest/t/MultiTestDB.conf
    - cp -f ensembl/travisci/MultiTestDB.conf.travisci.mysql  ensembl/modules/t/MultiTestDB.conf
    - cd tabix
    - make
    - cd perl
    - perl Makefile.PL
    - make && make install
    - cd ../../
    - cd htslib
    - make
    - export HTSLIB_DIR=$(pwd -P)
    - cd ../
    - cd Bio-HTS
    - perl Build.PL --htslib $HTSLIB_DIR
    - ./Build
    - cd ../

script: "./travisci/harness.sh"

# Get the matrix to only build coveralls support when on 5.10
matrix:
  exclude:
    - perl: "5.10"
      env: COVERALLS=true
    - perl: "5.14"
      env: COVERALLS=false

